# Generated by Django 2.0.4 on 2018-04-04 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('repeticiones', models.IntegerField()),
                ('series', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ejercicio', models.ManyToManyField(blank=True, null=True, to='Gymapp.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='recepcionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='horarios',
            field=models.ManyToManyField(blank=True, null=True, to='Gymapp.horario'),
        ),
        migrations.AddField(
            model_name='gym',
            name='recepcionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gymapp.recepcionista'),
        ),
    ]
